query getBookings {
    bookings(where: {is_deleted: {_eq: false}, room_id: {_is_null: true}}) {
        id
        duration
        created_at
        is_paid
        is_available
        resident {
          id
          email
          name
          level
          nationality
          telephone
          institution
        }
    }
}