query getBookings {
    bookings {
        id
        duration
        created_at
        is_paid
        resident {
          id
          email
          name
          level
          nationality
          telephone
          institution
        }
    }
}