query getFiveBookings {
  bookings(limit: 5, where: {room_id: {_is_null: true}, is_deleted: {_eq: false}}) {
      id
      created_at
      is_paid
      is_available
      resident {
        id
        name
        level
        institution
      }
  }
}

