query getResidents {
  residents(where: {is_approved: {_eq: true}}) {
    id
    institution
    level
    name
    telephone
    bookings {
      duration
      room {
        name
      }
    }
  }
}