query getRoomDetails($id: uuid!) {
  rooms(where: {id: {_eq: $id}}) {
    id
    name
    last_updated
    created_at
    room_type {
      title
      number_of_occupants
      amount_12_months_duration
      amount_9_months_duration
    }
  }
}